New --timeout / --poll-timeout options
`--poll-timeout` sets the timeout used in calls to `zmq_poll` (for
commands that use that).  `--timeout` is a shortcut operator for setting
the poll, send and receive timeouts, as well as the `--linger`.

Closes #3

diff --git a/t/lib b/t/lib
--- a/t/lib
+++ b/t/lib
@@ -4,6 +4,21 @@ DATADIR=$(mktemp -d)
 DATAFILE=${DATADIR}/data
 trap 'rm -rf ${DATADIR}' EXIT TERM QUIT
 
+file_is_empty() {
+	file=$1
+	msg=${2:-$(basename ${file}) should be empty}
+	if [[ -f ${file} && -s ${file} ]]; then
+		echo >&2 "${msg}: FAILED"
+		echo >&2 "   file was not empty.  it contained:"
+		echo >&2 "   -----------------------------------------------"
+		cat ${file} | sed -e 's/^/   /'
+		echo >&2 "   -----------------------------------------------"
+		echo >&2
+		echo FAIL
+		exit 1
+	fi
+}
+
 line_ok() {
 	file=$1
 	line=$2
